### ISSUE TITLE
Unable to install plugin on static-site example

### ISSUE THREAD

**Issue by growdigital** [krambuhl/metalsmith-rewrite#2]
I can’t manage to get metalsmith-rewrite to work at all on the Metalsmith static-site example. I’m sure it’s something I’m doing but not sure how to start troubleshooting. Here are my steps to re-create issue:

1. Download [`static-site` example](https://github.com/segmentio/metalsmith/tree/master/examples/static-site) and run `$ npm install`
2. Install metalsmith-rewrite with `$ npm install metalsmith-rewrite --save-dev`
3. Add require to index.js
4. Add dummy content to `/src/blog/directory/src.html`
5. Add following to `index.js`, after markdown and before permalinks:
```
.use(rewrite({
    pattern: 'blog/**/*.html',
    filename: 'blog/{date}/build.html',
    date: 'YYYY/MM'
}))
```
6. Run `$ make build`
7. `/build/blog/directory/src/index.html` is created, rather than `/build/blog/2017/06/build.html`

Gist for index.js: 
https://gist.github.com/growdigital/cd24b00d1c8150af8baa9000d534ac36

**Comment by growdigital** [comment]
I created a test repo for this:
https://github.com/growdigital/metalsmith-rewrite-test

`https://github.com/growdigital/metalsmith-rewrite-test/tree/master/build/blog/directory/src/index.html` 

is created rather than:

`https://github.com/growdigital/metalsmith-rewrite-test/tree/master/build/blog/2017/06/build.html`

**Comment by krambuhl** [comment]
This is not working because the matched file does not have metadata.  File renaming is skipped when the filename pattern is missing required information.  

Sorry about the forever reply, I'm not actively working with metalsmith currently. hopefully you were able to find a solution.

**Comment by growdigital** [comment]
no probs, thank you for getting back to me :) I managed to get something else working, will have a look at this again
